import { afterEach, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { reviewArtifactMedia, reviewArtifactPreview } from "./artifact-media.js";
import { recordSessionArtifact } from "./session-artifacts.js";
import type { ServerConfig, WorkspaceInfo } from "./types.js";

const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true }); });
async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "ipw-artifact-media-")); roots.push(root);
  const workspace: WorkspaceInfo = { id: "ws", name: "Test", path: root, preset: "starter", workspaceType: "local" };
  const config: ServerConfig = {
    host: "127.0.0.1", port: 0, token: "test", hostToken: "host", configPath: join(root, "server.json"),
    approval: { mode: "auto", timeoutMs: 0 }, corsOrigins: [], workspaces: [workspace], authorizedRoots: [root],
    readOnly: false, startedAt: Date.now(), tokenSource: "generated", hostTokenSource: "generated", logFormat: "pretty", logRequests: false,
  };
  const context = { workspaceId: "ws", sessionId: "session" };
  const sourcePath = "design/session-artifact-slides/entry.html";
  const directory = join(root, "design/session-artifact-slides");
  await mkdir(join(directory, "assets"), { recursive: true });
  await writeFile(join(directory, "entry.html"), "<h1>Autumn</h1>");
  await writeFile(join(directory, "brief.json"), JSON.stringify({ title: "Autumn" }));
  const queries: string[] = [];
  const query = async (id: string) => { queries.push(id); return { ok: true, result: { models: [] } }; };
  const review = (args: Record<string, unknown>) => reviewArtifactMedia(config, { sourcePath, ...args }, context, query);
  const needs = [{ id: "cover", purpose: "Illustrative autumn alley atmosphere, not documentary evidence", kind: "image" }];
  return { root, directory, config, workspace, context, sourcePath, queries, query, review, needs };
}

test("missing plan cannot pass the automatic delivery check", async () => {
  const f = await fixture();
  expect((await f.review({ phase: "check" })).result).toMatchObject({ fileCanBeDelivered: false, issues: ["missing_media_plan"] });
});

test("MCP calls without session metadata plan and check the explicit artifact owner", async () => {
  const f = await fixture();
  const context = { workspaceId: "ws" };
  const review = (args: Record<string, unknown>) => reviewArtifactMedia(f.config, { sourcePath: f.sourcePath, ...args }, context, f.query);
  await review({ phase: "plan", needs: [{ id: "diagram", purpose: "Editable task diagram", kind: "diagram" }] });
  expect((await review({ phase: "check", outcomes: [{ id: "diagram", status: "diagram" }] })).result).toMatchObject({ complete: true });
  await expect(reviewArtifactMedia(f.config, { sourcePath: f.sourcePath, phase: "check" }, { workspaceId: "ws", sessionId: "other" }, f.query)).rejects.toThrow("calling session");
  await expect(reviewArtifactMedia(f.config, { sourcePath: f.sourcePath, phase: "check" }, { workspaceId: "ws", sessionId: "" }, f.query)).rejects.toThrow("valid sessionId");
});

test("metadata-free media checks cannot borrow another conversation's generation receipt", async () => {
  const f = await fixture();
  const context = { workspaceId: "ws" };
  const sourcePath = "video/second-artifact-video-2/index.html";
  const directory = join(f.root, "video/second-artifact-video-2");
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "brief.json"), "{}");
  await writeFile(join(directory, "index.html"), '<img src="scene.png">');
  await writeFile(join(directory, "scene.png"), "generated bytes");
  await writeFile(join(f.root, "generated.png"), "generated bytes");
  const review = (args: Record<string, unknown>) => reviewArtifactMedia(f.config, { sourcePath, ...args }, context, f.query);
  await review({ phase: "plan", needs: f.needs });
  await recordSessionArtifact(f.config, f.workspace, "session", "generated.png", undefined, { id: "gen", kind: "image", model: "test", completedAt: Date.now() });
  const outcomes = [{ id: "cover", status: "generated", path: "scene.png", generationPath: "generated.png" }];
  expect((await review({ phase: "check", outcomes })).result).toMatchObject({ issues: ["cover: missing_generation_receipt"] });
  await recordSessionArtifact(f.config, f.workspace, "second", "generated.png", undefined, { id: "gen-second", kind: "image", model: "test", completedAt: Date.now() });
  expect((await review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
});

test("a missing planned entry returns a structured delivery failure", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await rm(join(f.directory, "entry.html"));
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: false, fileCanBeDelivered: false, issues: ["missing_source"] });
});
test("planning queries actual capabilities once per kind and preserves the brief", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: [...f.needs, { id: "second", purpose: "Second scene", kind: "image" }] });
  expect(f.queries).toEqual(["openai-image-generation"]);
  expect(JSON.parse(await readFile(join(f.directory, "brief.json"), "utf8")).title).toBe("Autumn");
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: false });
});
test("explicit no-generation scope needs no provider query", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: [], exemption: "no-generation", reason: "User requested no generated media" });
  expect(f.queries).toEqual([]);
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: true });
  await expect((await fixture()).review({ phase: "plan", needs: [] })).rejects.toThrow("exemption");
});
test("pending imagery cannot be erased by re-planning or changing it to geometry", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await expect(f.review({ phase: "plan", needs: [], exemption: "diagrams-sufficient", reason: "I prefer shapes" })).rejects.toThrow("already exists");
  expect((await f.review({ phase: "check", outcomes: [{ id: "cover", status: "diagram" }] })).result).toMatchObject({ fileCanBeDelivered: false, issues: ["cover: planned_imagery_replaced_by_diagram"] });
});
test("existing assets must be nonempty and actually referenced, not just mentioned", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), '<p>assets/scene.png</p><!-- <img src="assets/scene.png"> -->');
  const outcomes = [{ id: "cover", status: "reused", path: "assets/scene.png" }];
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: false });
  await writeFile(join(f.directory, "entry.html"), '<img src="assets/scene.png">');
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
  await writeFile(join(f.directory, "assets/scene.png"), "");
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: false });
});

test("accepts a workspace-relative outcome path as well as a session-relative path", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), '<img src="assets/scene.png">');
  const workspacePath = "design/session-artifact-slides/assets/scene.png";
  expect((await f.review({ phase: "check", outcomes: [{ id: "cover", status: "reused", path: workspacePath }] })).result).toMatchObject({ complete: true });
});

test("checks actual media in root-mounted HyperFrames compositions with runtime path semantics", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await mkdir(join(f.directory, "compositions/frames"), { recursive: true });
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="compositions/frames/scene.html?rev=1" data-composition-id="scene"></section>');
  const outcomes = [{ id: "cover", status: "reused", path: "assets/scene.png" }];
  for (const src of ["../../assets/scene.png", "assets/scene.png"]) {
    await writeFile(join(f.directory, "compositions/frames/scene.html"), `<div data-composition-id="scene"><img src="${src}"></div>`);
    expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
  }
});

test("only the mounted composition template and real CSS URLs count as placement", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await mkdir(join(f.directory, "compositions"));
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="compositions/scene.html" data-composition-id="scene"></section>');
  const outcomes = [{ id: "cover", status: "reused", path: "assets/scene.png" }];
  await writeFile(join(f.directory, "compositions/scene.html"), `
    <template id="unused-template"><img src="assets/scene.png"></template>
    <template id="scene-template"><p>url(assets/scene.png)</p>
      <img data-src="assets/scene.png" alt="src='assets/scene.png'">
      <script>const example = '<img src="assets/scene.png">';</script>
      <style>/* .x{background:url(assets/scene.png)} */ .x:after{content:"url(assets/scene.png)"}</style>
    </template>`);
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ issues: ["cover: empty_or_unreferenced_asset"] });
  await writeFile(join(f.directory, "compositions/scene.html"), '<template id="scene-template"><div style="background-image:url(&quot;../assets/scene.png&quot;)"></div></template>');
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
});

test("follows composition stylesheet imports once, including cycles", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await mkdir(join(f.directory, "compositions"));
  await mkdir(join(f.directory, "styles"));
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="compositions/scene.html"></section>');
  await writeFile(join(f.directory, "compositions/scene.html"), '<link rel="stylesheet" href="../styles/scene.css?rev=2"><div class="hero"></div>');
  await writeFile(join(f.directory, "styles/scene.css"), '@import "nested.css";');
  await writeFile(join(f.directory, "styles/nested.css"), '@import url("scene.css");.hero{background-image:url(../assets/scene.png)}');
  expect((await f.review({ phase: "check", outcomes: [{ id: "cover", status: "reused", path: "assets/scene.png" }] })).result).toMatchObject({ complete: true });
  await writeFile(join(f.directory, "compositions/scene.html"), '<html><head><link rel="stylesheet" href="scene.css"></head><body><template><div class="hero"></div></template></body></html>');
  await writeFile(join(f.directory, "compositions/scene.css"), '@import "../styles/nested.css";');
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: true });
});

test("unbound variable strings, scripts and unloaded nested compositions do not prove media usage", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await mkdir(join(f.directory, "compositions"));
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "entry.html"), `
    <!-- <section data-composition-src="missing.html"></section> -->
    <script>const example = '<section data-composition-src="missing.html"></section>';</script>
    <section data-composition-src="compositions/scene.html" data-variable-values='{"imageUrl":"assets/scene.png"}'></section>`);
  await writeFile(join(f.directory, "compositions/scene.html"), '<section data-composition-src="compositions/nested.html"></section>');
  await writeFile(join(f.directory, "compositions/nested.html"), '<img src="assets/scene.png">');
  expect((await f.review({ phase: "check", outcomes: [{ id: "cover", status: "reused", path: "assets/scene.png" }] })).result).toMatchObject({ issues: ["cover: empty_or_unreferenced_asset"] });
});

test("local mounted templates take precedence over external composition content", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.directory, "assets/scene.png"), "image");
  await writeFile(join(f.directory, "scene.html"), '<img src="assets/scene.png">');
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="scene.html" data-composition-id="scene"></section><template id="scene-template"><p>Text only</p></template>');
  const outcomes = [{ id: "cover", status: "reused", path: "assets/scene.png" }];
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ issues: ["cover: empty_or_unreferenced_asset"] });
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="missing.html" data-composition-id="scene"></section><template id="scene-template"><img src="assets/scene.png"></template>');
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
});

test("missing mounted compositions and stylesheets prevent delivery with repairable paths", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: [], exemption: "explicit-text-only", reason: "Text video" });
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="compositions/missing.html"></section><link rel="stylesheet" href="styles/missing.css">');
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: false, fileCanBeDelivered: false, issues: ["missing_stylesheet: styles/missing.css", "missing_composition: compositions/missing.html"] });
});

test("composition and stylesheet dependencies cannot escape the artifact root", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.root, "outside.html"), '<img src="assets/scene.png">');
  await symlink(join(f.root, "outside.html"), join(f.directory, "linked.html"));
  for (const html of [
    '<section data-composition-src="../../outside.html"></section>',
    '<section data-composition-src="linked.html"></section>',
    '<link rel="stylesheet" href="../../outside.css">',
  ]) {
    await writeFile(join(f.directory, "entry.html"), html);
    await expect(f.review({ phase: "check" })).rejects.toThrow("escapes");
  }
});

test("dependency traversal keeps composition count and stylesheet count bounded", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.directory, "entry.html"), Array.from({ length: 33 }, (_, i) => `<section data-composition-src="${i}.html"></section>`).join(""));
  await expect(f.review({ phase: "check" })).rejects.toThrow("Too many composition hosts");
  await writeFile(join(f.directory, "entry.html"), Array.from({ length: 13 }, (_, i) => `<link rel="stylesheet" href="${i}.css">`).join(""));
  await expect(f.review({ phase: "check" })).rejects.toThrow("Too many stylesheets");
});

test("dependency traversal bounds individual and cumulative file sizes", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.directory, "entry.html"), '<section data-composition-src="large.html"></section>');
  await writeFile(join(f.directory, "large.html"), " ".repeat(2 * 1024 * 1024 + 1));
  await expect(f.review({ phase: "check" })).rejects.toThrow("bounded regular file");
  await writeFile(join(f.directory, "entry.html"), Array.from({ length: 5 }, (_, i) => `<section data-composition-src="${i}.html"></section>`).join(""));
  for (let i = 0; i < 5; i++) await writeFile(join(f.directory, `${i}.html`), " ".repeat(1800 * 1024));
  await expect(f.review({ phase: "check" })).rejects.toThrow("dependencies exceed 8 MB");
});
test("generated copies require a real session receipt and matching bytes; check revalidates saved outcomes", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.root, "generated.png"), "generated bytes");
  await writeFile(join(f.directory, "assets/scene.png"), "generated bytes");
  await writeFile(join(f.directory, "entry.html"), '<link rel="stylesheet" href="theme.css"><div class="hero"></div>');
  await writeFile(join(f.directory, "theme.css"), '.hero{background-image:url("assets/scene.png")}');
  const outcomes = [{ id: "cover", status: "generated", path: "assets/scene.png", generationPath: "generated.png" }];
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ issues: ["cover: missing_generation_receipt"] });
  await recordSessionArtifact(f.config, f.workspace, "session", "generated.png", undefined, { id: "gen", kind: "image", model: "test", completedAt: Date.now() });
  await f.review({ phase: "plan", needs: f.needs });
  expect((await f.review({ phase: "check", outcomes })).result).toMatchObject({ complete: true });
  expect((await f.review({ phase: "check" })).result).toMatchObject({ complete: true });
  await writeFile(join(f.directory, "assets/scene.png"), "different bytes");
  expect((await f.review({ phase: "check" })).result).toMatchObject({ issues: ["cover: generated_file_mismatch"] });
});
test("unavailable or failed media allows disclosed file delivery without claiming media completion", async () => {
  const f = await fixture();
  await f.review({ phase: "plan", needs: f.needs });
  expect((await f.review({ phase: "check", outcomes: [{ id: "cover", status: "unavailable", reason: "No authorized image model in status response" }] })).result)
    .toMatchObject({ fileCanBeDelivered: true, complete: false, reportedFallbacks: ["cover: unavailable: No authorized image model in status response"] });
});
test("query failure remains unknown and does not prevent saving a plan", async () => {
  const f = await fixture();
  const result = await reviewArtifactMedia(f.config, { sourcePath: f.sourcePath, phase: "plan", needs: f.needs }, f.context, async () => { throw new Error("offline"); });
  expect(result.result).toMatchObject({ capabilities: [{ kind: "image", status: "unknown" }] });
});
test("rejects escaping paths and symlinks, and respects read-only workspaces", async () => {
  const f = await fixture();
  await expect(reviewArtifactMedia({ ...f.config, readOnly: true }, { sourcePath: f.sourcePath, phase: "plan", needs: f.needs }, f.context, f.query)).rejects.toThrow("read-only");
  await f.review({ phase: "plan", needs: f.needs });
  await writeFile(join(f.root, "outside.png"), "outside");
  await symlink(join(f.root, "outside.png"), join(f.directory, "assets/link.png"));
  await expect(f.review({ phase: "check", outcomes: [{ id: "cover", status: "reused", path: "../../outside.png" }] })).rejects.toThrow("escapes");
  await expect(f.review({ phase: "check", outcomes: [{ id: "cover", status: "reused", path: "assets/link.png" }] })).rejects.toThrow("escapes");
});

test("explicit engine workspace id wins over the first project and stale directory", async () => {
  const first = await fixture();
  const selected = await fixture();
  first.config.workspaces = [first.workspace, { ...selected.workspace, id: "selected" }];
  const context = { sessionId: "session", workspaceId: "selected", directory: first.root };
  await reviewArtifactMedia(first.config, { phase: "plan", sourcePath: selected.sourcePath, needs: selected.needs }, context, selected.query);
  expect(JSON.parse(await readFile(join(first.directory, "brief.json"), "utf8")).mediaPlan).toBeUndefined();
  expect(JSON.parse(await readFile(join(selected.directory, "brief.json"), "utf8")).mediaPlan.needs).toEqual(selected.needs);
  await expect(reviewArtifactMedia(first.config, { phase: "check", sourcePath: selected.sourcePath }, { ...context, workspaceId: "missing" }, selected.query)).rejects.toThrow("requested workspace");
});

test("client preview review always checks the current rendered dependencies", async () => {
  const f = await fixture();
  const calls: Array<{ workspaceId: string; sourcePath: string; kind: "site" | "slides" }> = [];
  const run = async (input: { workspaceId: string; sourcePath: string; kind: "site" | "slides" }) => {
    calls.push(input);
    return { ok: true, result: { passed: true, pageCount: 1, issues: [] } };
  };
  const input: { sourcePath: string; kind: "slides" } = { sourcePath: f.sourcePath, kind: "slides" };
  expect((await reviewArtifactPreview(f.config, input, f.context, run)).result).toMatchObject({ passed: true, pageCount: 1 });
  expect((await reviewArtifactPreview(f.config, input, f.context, run)).result).toMatchObject({ passed: true, pageCount: 1 });
  expect(calls).toHaveLength(2);
  await writeFile(join(f.directory, "entry.html"), "<h1>Revised autumn</h1>");
  await reviewArtifactPreview(f.config, input, f.context, run);
  expect(calls).toHaveLength(3);
  expect(JSON.parse(await readFile(join(f.directory, "brief.json"), "utf8")).previewReview).toMatchObject({
    sourcePath: f.sourcePath,
    kind: "slides",
    result: { passed: true, pageCount: 1 },
  });
});
