/** Executable-format example for the existing HyperFrames parser, not a second schema. */
export const VIDEO_STORYBOARD_EXAMPLE = `---
format: 1920x1080
message: Turn an idea into a working team
audience: Independent founders
theme: ai-auto
visual_style: Clear product UI, layered space, readable typography
music_prompt: Restrained instrumental pulse beneath narration
---

## Frame 1 — The idea takes shape
- scene: An idea card becomes a three-step plan; the focus moves to the first task.
- duration: 5s
- voiceover: One idea becomes the next clear step.
- voice_id: auto
- camera: fixed:progressive-build
- transition_in: cut
- asset_source: code
- asset_brief: Editable idea and task cards; no external visual required.
- sound_effects: A quiet click when the first task appears, if an actual effect is available.
- status: outline

Coverage: C1 (brief: turn an idea into a next action) → Frame 1 narration and visible task cards. No source file supplied; this is an illustrative concept, not a factual case study.
Shot fit: The viewer follows one idea becoming actionable tasks. A fixed progressive build reveals their order and lands on the first task; a spatial fly-through would interrupt reading.
Rhythm: Orient with the idea, develop its three tasks, then resolve with a next action. Calm instructional pacing; no promotional climax required.
Beat binding: “One idea” → idea card; “becomes the next clear step” → reveal connected tasks and emphasize the first. Visual need: editable task cards; no footage search needed.
Continuity: Reuse the same idea card identity and palette through the transformation. Narration: natural phrase boundary after “idea”; keep this direction out of spoken text and do not claim an exact audio pause.
0–1s establish the idea; 1–4s reveal and connect tasks; 4–5s hold the first action.
`;

export const VIDEO_STORYBOARD_FORMAT_CONTRACT = [
  "- Bound the script draft stage: read the source and inventory coverage once, identify the driver (speech, dialogue, visible action, music, footage or silent reading), then choose one content-led shot sequence. Make one rough duration estimate per shot; for spoken shots use one rough narration-duration estimate per shot (about 4 CJK characters or 2.5 Latin words per second, plus purposeful reading holds), otherwise use the intended action, source media or reading need. Use a single counting calculation when needed; never repeatedly hand-count characters or compare near-identical narration versions to fit an approximate target. Approximate targets are not strict caps. Define audience changes and observable events, shortlist executable recipes by intent, input and capacity, then save the complete native STORYBOARD.md with status: outline and estimated positive durations as soon as coverage, applicable spoken lines and concrete shot treatments are settled, before media acquisition or production. Beat ranges in this draft are provisional scene-relative planning windows, not word alignment: do not calculate per-word, per-phrase or frame-accurate timestamps before synthesis. Combine the source/semantic and saved-format checks into one post-save review and repair observed defects together; reopen only affected shots when facts, user edits, a failed check or measured media introduce new evidence. Preserve required facts and explicit user caps; an irreconcilable cap needs one consequential user choice, not deletion, accelerated speech or endless estimation. After saving, use measured speech/media cues and provider alignment where applicable to retime dependent beats; without word alignment use honest sentence-level captions, never character-proportional word timestamps. This is an execution guideline, not a runtime timeout or a guarantee of model latency.",
  "- Bind each narrative event to its intended audience change, visible subject/action, applicable exact spoken phrase, dialogue turn, footage moment, music cue or silent reading order, required asset or recipe input, and readable result/hold in that frame's existing narrative. Keep events in causal or viewing order. Narrated events bind to exact spoken phrases; one sentence may span events, and adjacent phrases may share an event. Do not invent narration for a visual-, dialogue- or music-led scene merely to fill a field. For search/import needs, write one concrete query per distinct visual need (subject + action + setting, with date/location when factual), optional English/local-language equivalent and exclusion criteria. Reuse identical needs across beats; no fixed keyword quota or whole-video generic keyword list. Verify source relevance, provenance and license before choosing footage. If a claim needs a diagram or exact data, use editable graphics instead of loosely related B-roll.",
  "- For a generated asset, derive asset_brief from subject/identity + environment + action/change + framing/camera + semantic timing + final state + style + needed sound; omit irrelevant parts and respect the selected model's actual capabilities and duration limits. Each supplied reference must have an explicit role: identity/product, setting, style, first/last state, motion or audio. Record exact project paths, what to preserve and what may change in frame notes. Resolve conflicting references from user priorities, asking only for consequential ambiguity. Maintain recurring subject appearance, product details, location geometry, palette and screen direction across connected shots. Do not copy a reference's factual claims or unwanted text, or invent @reference syntax, uploads or generated audio for a provider that does not support them.",
  "- Plan narration for natural speech: meaningful phrase boundaries, pronunciation of names/abbreviations/numbers, emphasis and purpose-led breath/reading pauses. Keep stage directions and pause markers out of voiceover spoken text; store them in frame notes. Apply only supported delivery controls consistent with the saved voice/user request; do not invent pauseSeconds or SSML support, override a pinned voice or add unrequested voice instructions. A visual hold is not an inserted audio pause. After synthesis, map captions, callouts and focus changes to real provider word timings and measured audio, preserving the timing sidecar. Without word alignment, use honest sentence-level captions, not evenly divided word timestamps. If exact audible pauses are required but unsupported, disclose the gap rather than claiming precise silence. Recheck transcript and all dependent beats/captions after narration edits.",
  "- Plan a genre-appropriate whole-video rhythm in the first frame's notes: hook/orientation, development/evidence, resolution or requested action, with relative energy and information density rather than fixed scene counts or percentages. Explain how each shot contributes. Technical/course material prioritizes dependency order and reading time; document/factual stories prioritize context and evidence; promotional reveals may use stronger contrast, while quiet stories need not end in a sales CTA. Each shot recipe records entry state, focal subject, content change, resolved state, readable hold, transition intent and relevant limits, using the existing temporal-pattern/component map. Vary rhythm at meaningful changes, not arbitrary camera switches; do not force fast travel, compulsory slow motion, once-per-preset quotas or music-beat cuts on every genre. Use real measured audio cues only when music-led timing is appropriate.",
  "- Before splitting shots, inventory the supplied source's important claims, steps, figures and qualifications. Keep a compact source coverage map in the existing frame narrative: point ID → source heading/page/paragraph → frame(s) → spoken or visibly explained evidence. Put intentional omissions and their reasons in the first frame's notes. For a brief without source files, trace requirements to shots instead; never invent source anchors. Preserve names, numbers, units, causal relationships and meaningful parentheses/qualifiers. Required points must be covered; an explicit duration cap that cannot fit them needs a user choice, not silent deletion or rushed narration.",
  "- Choose shots from intended audience change → observable event/evidence → matching executable recipe intent and capacity → motivated camera treatment. An event may change understanding, decision, relationship, emotion, action or state; it need not be a spoken teaching point. Record the fit rationale in each frame's narrative. Keep process/technical steps readable with fixed framing and local reveals; compare before/after at matching viewpoints and scales; use spatial travel only when spatial relationships are the subject. A library match, cinematic preset or attractive stock clip is not proof of suitability. Decide readable holds before motion and keep illustrative media distinct from factual evidence.",
  "- Before production, re-read the source and saved storyboard: reconcile every required coverage point with actual spoken/visible content, check recipe fit and readable holds, and repair contradictions, missing qualifications or unsupported claims. List unresolved source gaps explicitly rather than reporting the script ready. This is agent semantic self-review, not a deterministic parser or rendered-quality verdict; do not claim a source check or audition that did not happen.",
  "- STORYBOARD.md MUST use the native parser format shown below: whole-video settings inside the leading --- frontmatter; every frame field on its own physical line starting with `- key: value`. Never combine fields into a semicolon-separated paragraph, a Markdown pipe table, translated keys or a code fence around the saved file. Omit unknown optional lines entirely; never write literal `omit`, `null` or invented asset paths. Keep extra direction/beat maps in narrative paragraphs AFTER the metadata. Adapt the example content and shot count to the brief, not the syntax.",
  "```markdown",
  VIDEO_STORYBOARD_EXAMPLE.trimEnd(),
  "```",
  "- Before reporting the script ready, re-read the saved file and verify frontmatter, one Frame heading per shot, separate metadata list lines, non-empty scene content, and positive duration. Resolve every camera field to a concrete content-led treatment. Fixed framing with progressive local reveals is valid; use `component:spatial-camera-suite#<shotStyle>` only when spatial traversal benefits that shot. The user reviews this file in the existing Studio script table; link its exact project path as the editable script, not a generic planning document.",
].join("\n");

/** Only a project-owned canonical script should open the video editor. */
export function videoProjectIdFromStoryboardPath(path: string): string | null {
  const normalized = path.trim().replaceAll("\\", "/").replace(/^\.\//, "");
  const match = /^video\/([^/]+)\/STORYBOARD\.md$/i.exec(normalized);
  return match && match[1] !== "." && match[1] !== ".." ? match[1]! : null;
}
